version: '3.8'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile
    ports:
      - '3000:3000'
    restart: always
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_NOTIFICATIONS_WS_URL: ${VITE_NOTIFICATIONS_WS_URL}
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/apps/web/node_modules
    working_dir: /app/apps/web
    networks:
      - challenge-public-network
    command: npm run dev -- --host 0.0.0.0

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/docker/Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      PORT: 3001
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      TASKS_SERVICE_BASE_URL: ${TASKS_SERVICE_BASE_URL}
      USERS_TASKS_SERVICE_BASE_URL: ${USERS_TASKS_SERVICE_BASE_URL}
      USERS_SERVICE_BASE_URL: ${USERS_SERVICE_BASE_URL}
      TASK_AUDIT_LOGS_SERVICE_BASE_URL: ${TASK_AUDIT_LOGS_SERVICE_BASE_URL}
      NOTIFICATIONS_SERVICE_BASE_URL: ${NOTIFICATIONS_SERVICE_BASE_URL}
      BROKER_URL: ${BROKER_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      # - .:/app
      # - /app/node_modules
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./packages:/app/packages
      - /app/apps/api-gateway/node_modules
    working_dir: /app/apps/api-gateway
    depends_on:
      auth-service-db:
        condition: service_started
      notifications-service-db:
        condition: service_started
      tasks-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-public-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: apps/auth-service/docker/Dockerfile
    ports:
      - '3002:3002'
    restart: always
    environment:
      PORT: 3002
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DB_AUTH_SERVICE_PASSWORD: ${DB_AUTH_SERVICE_PASSWORD}
      DB_AUTH_SERVICE_USER: ${DB_AUTH_SERVICE_USER}
      DB_AUTH_SERVICE_NAME: ${DB_AUTH_SERVICE_NAME}
      DB_AUTH_SERVICE_HOST: ${DB_AUTH_SERVICE_HOST}
      DB_AUTH_SERVICE_PORT: ${DB_AUTH_SERVICE_PORT}
    volumes:
      # - .:/app
      # - /app/node_modules
      - ./apps/auth-service:/app/apps/auth-service
      - ./packages:/app/packages
      - /app/apps/auth-service/node_modules
    working_dir: /app/apps/auth-service
    depends_on:
      auth-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-public-network

  tasks-service:
    container_name: tasks-service
    build:
      context: .
      dockerfile: apps/tasks-service/docker/Dockerfile
    ports:
      - '3003:3003'
    restart: always
    environment:
      PORT: 3003
      DB_TASKS_SERVICE_PASSWORD: ${DB_TASKS_SERVICE_PASSWORD}
      DB_TASKS_SERVICE_USER: ${DB_TASKS_SERVICE_USER}
      DB_TASKS_SERVICE_NAME: ${DB_TASKS_SERVICE_NAME}
      DB_TASKS_SERVICE_HOST: ${DB_TASKS_SERVICE_HOST}
      DB_TASKS_SERVICE_PORT: ${DB_TASKS_SERVICE_PORT}
      BROKER_URL: ${BROKER_URL}
    volumes:
      - ./apps/tasks-service:/app/apps/tasks-service
      - ./packages:/app/packages
      - /app/node_modules
    working_dir: /app/apps/tasks-service
    depends_on:
      tasks-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-public-network

  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: apps/notifications-service/docker/Dockerfile
    ports:
      - '3004:3004'
    restart: always
    environment:
      PORT: 3004
      DB_NOTIFICATIONS_SERVICE_PASSWORD: ${DB_NOTIFICATIONS_SERVICE_PASSWORD}
      DB_NOTIFICATIONS_SERVICE_USER: ${DB_NOTIFICATIONS_SERVICE_USER}
      DB_NOTIFICATIONS_SERVICE_NAME: ${DB_NOTIFICATIONS_SERVICE_NAME}
      DB_NOTIFICATIONS_SERVICE_HOST: ${DB_NOTIFICATIONS_SERVICE_HOST}
      DB_NOTIFICATIONS_SERVICE_PORT: ${DB_NOTIFICATIONS_SERVICE_PORT}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      BROKER_URL: ${BROKER_URL}
    volumes:
      - ./apps/notifications-service:/app/apps/notifications-service
      - ./packages:/app/packages
      - /app/apps/notifications-service/node_modules
    working_dir: /app/apps/notifications-service
    depends_on:
      notifications-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-public-network

  auth-service-db:
    image: postgres:17-alpine
    container_name: auth-service-db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - auth-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_AUTH_SERVICE_PASSWORD}
      POSTGRES_USER: ${DB_AUTH_SERVICE_USER}
      POSTGRES_DB: ${DB_AUTH_SERVICE_NAME}
    networks:
      - challenge-public-network

  notifications-service-db:
    image: postgres:17-alpine
    container_name: notifications-service-db
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - notifications-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_NOTIFICATIONS_SERVICE_PASSWORD}
      POSTGRES_USER: ${DB_NOTIFICATIONS_SERVICE_USER}
      POSTGRES_DB: ${DB_NOTIFICATIONS_SERVICE_NAME}
    networks:
      - challenge-public-network

  tasks-service-db:
    image: postgres:17-alpine
    container_name: tasks-service-db
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - tasks-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_TASKS_SERVICE_PASSWORD}
      POSTGRES_USER: ${DB_TASKS_SERVICE_USER}
      POSTGRES_DB: ${DB_TASKS_SERVICE_NAME}
    networks:
      - challenge-public-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/logs/rabbitmq
    networks:
      - challenge-public-network

volumes:
  auth-pg-data:
    driver: local
  notifications-pg-data:
    driver: local
  tasks-pg-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local

networks:
  challenge-public-network:
    driver: bridge
