name: Build Docker Images

on:
  workflow_run:
    workflows: ['JungleOps CI']
    types:
      - completed

jobs:
  build-and-push:
    name: Build and push Docker Image
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dkadadev
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build affected images
        run: npx turbo run docker:build

      - name: Push images
        run: |
          docker push dkadadev/jungleops-api-gateway:latest
          docker push dkadadev/jungleops-auth-service:latest
          docker push dkadadev/jungleops-notifications-service:latest
          docker push dkadadev/jungleops-tasks-service:latest
          docker push dkadadev/jungleops-web:latest
